### ISSUE TITLE
Criar sessão do usuário;

### ISSUE THREAD

**Issue by AdrielSantana** [SIEHP/siehp-webapp#33]
## Descrição

Utilizar Zustand e Zod para criar uma sessão do usuário e atribuir o token ao header da requisição do Axios;

https://doichevkostia.dev/blog/authentication-store-with-zustand/

## Testes

1. Fazer uma requisição avulsa e checar se está com um token no header

## GitFlow

Criar uma Branch a partir de: `dev`

É necessário abrir uma PR para as branchs a seguir:

- [ ] `main`
- [ ] `dev`

**Comment by AdrielSantana** [comment]
Mover caso de usos, e coisas referentes para o módulo e Users

Fazer uma integração com o React Query (Analizar issue #34)

Realizar a página de /example como testes

**Comment by AdrielSantana** [comment]
https://docs.pmnd.rs/zustand/guides/nextjs

**Comment by Vitordotpy** [comment]
Durante o desenvolvimento da #36 foi encontrado um problema com o sistema de sessão que não está permitindo o usuário (mock) de ser recuperado através do auth em quaisquer página, em detrimento disso essa tarefa será finalizada e outra issue de correção deverá ser aberta.
