### ISSUE TITLE
NFPA03 - Arquitetura limpa e desenvolvimento voltado ao domínio.

### ISSUE THREAD

**Issue by Vitordotpy** [SIEHP/siehp-webapp#9]
## Descrição

Organização de pastas e arquivos de modo a seguir os conceitos de Clean Architecture e DDD
#6 #5

## Testes

Não necessitará de testes

## GitFlow

Criar uma Branch a partir de: `main`

É necessário abrir uma PR para as branchs a seguir:

- [x] `main`
- [x] `dev`

**Comment by AdrielSantana** [comment]
Aplicar no repositorio da API tbm
